spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.44.181:3306/mybatisplus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

#spring:
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://192.168.58.128:3306/mp?useSSL=false&serverTimezone=GMt&2B8
  #    username: user2
  #    password: 123456

logging:
  level:
    root: warn
    com.jonny.mybatisplus.mybatisplus.dao: trace
  pattern:
    console: '%p%m%n'

# 配置mybatis plus配置文件位置
mybatis-plus:
  mapper-locations:
    - mapper/*
